project_name: polywatch
builds:
  - id: polywatch
    main: ./cmd/polywatch
    goos:
      - linux
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    binary: polywatch

archives:
  - format: binary
    files:
      - LICENSE
      - pw.example.yml
