watchers:
  - name: "hot reload"
    method: polling
    recursive: true
    path: .
    patterns:
      - \.go$
    signal: TERM
    delay: 100ms
    stop_timeout: 3s
    cmd: >
      dlv debug --headless -l :2345 --api-version=2 --accept-multiclient --log --continue ./cmd/api
