name: Release CLI

on:
  release:
    types: [ created ]

jobs:
  releases-matrix:
    name: Release Executable Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux]
        goarch: [386, amd64, arm, arm64]
    steps:
      - uses: actions/checkout@v3
      - uses: wangyoucao577/go-release-action@v1.38
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          goversion: "1.20"
          project_path: "./cmd/polywatch"
          binary_name: polywatch
